### ISSUE TITLE
Simple restore does not work for a teacher

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-block_simple_restore#1]
I just backed up a course with backadel and cannot restore that course as the instructor of the course that was backed up in a new course for that same instructor.
## Steps to reproduce
1. As admin backup a course with kattest (or any unprivileged user) as the instructor (NOT A SYSTEM ADMIN).
2. Login as kattes (or whoever you chose above) and go into a new course shell.
3. Click either link in simplified restore.
4. You will see "No course backups found" as the return.

**Comment by philcali** [comment]
Believe it or not, this is by design. I asked early in implementation whether or not simple restore should look in the user's private files for backups, and I was given a "No".

You will find if you move the backup from the user private files to the course backups, then it works as expected.

So, we're looking in user private files for backup as well?

**Comment by rrusso** [comment]
????

This has nothing to do with private files, nor should it. Please see me on this, there seems to be a fundamental misunderstanding as to how this needs to work.
1. Create a course with Dom Perignon as primary instructor.
2. Add stuff to it.
3. Schedule a backup with Backadel that includes that course.
4. Run cron.
5. Login as Dom Perignon and try to use simple restore to restore the course.
6. No worky.

**Comment by philcali** [comment]
Whoops, I probably should have read the line above **Steps to reproduce** to realize you mentioned backadel in the process.

Trying again..

**Comment by rrusso** [comment]
I believe the problem is that teachers are not able to access backadel's courses. Admins can without a problem, but not teachers as far as I can tell.

**Comment by philcali** [comment]
Right, that is absolutely the problem. I'm about to create a pull request that addresses this issue.

**Comment by rrusso** [comment]
Now it shows up as 0 bytes.

**Comment by rrusso** [comment]
## bad_backadel does not resolve all issues.
1. Logged in as an administrator, Simple Restore allows the admin to search for courses, then they are restored properly.
   - YAY!!!
2. Logged in as a lowly teacher, Simple Restore claims there are no backups available.
   - It does this even though we can verify the backup _teacher exists as admin.
   - I believe Moodle file.php is not allowing Simple Restore access to the backup file as an unprivileged user.

## Options
- What can we do about this?
- Did something change between 2.0.3 and 2.1, or was this overlooked in preliminary testing? @philcali said that he was administrator of the site when he tested Simple Restore. I've spent a ton of time on this and it seems like this everyday use case was never tested.
- How can we avoid this in the future?

**Comment by philcali** [comment]
I cannot replicate number 2 on your list. In my instance the appropriate backups show up for the appropriate person, under both Semesterly backups and Course backups. I've logged in as both unprivileged users and admins.

> Did something change between 2.0.3 and 2.1, or was this overlooked in preliminary testing? @philcali said that he was administrator of the site when he tested Simple Restore. I've spent a ton of time on this and it seems like this everyday use case was never tested.

All I can say is: **wow**.

**Comment by rrusso** [comment]
The problem is with backadel. It is tied to the automated course backup state. Once that state has changed, automated backups must run for courses to back up via backadel.

Reposting in backadel. I believe we can close and merge bad_backadel into master here and move on to the other issues.
