### ISSUE TITLE
Search function misbehaving

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-block_simple_restore#10]
# Security Issue

When logged in as kattest, `list.php` backups shows `backadel-GEC1_kattesting`
- This is a potential of a Faculty member's academic Freedom.
## Resolution

Please make it so that faculty members only see their own courses.
- Username matches should be exact when logged in as unprivileged users.
- Administrative searches can (and should) be flexible.

**Comment by philcali** [comment]
The appropriate regex for that would be something like:

`_username[_.]`

That would say get `_kattest_` or `_kattest.zip`. I think that would be pretty strict for username searches.

**Comment by philcali** [comment]
I'm checking my logic.

**Comment by philcali** [comment]
Continued discussion on issue #11.

**Comment by rrusso** [comment]
6067212 is totally broken.
