### ISSUE TITLE
Admin filter options unnecessary

### ISSUE THREAD

**Issue by philcali** [lsuits/lsu-block_simple_restore#12]
@rrusso brought to my attention how strangely the admin search options behave.

The reason for this behavior is because there are two locations to look from now.

_Contains_ is the only option that works for searching through backadel backups because that the only regex available. Instead of adding support for any other filter type, I would prefer to cut "equals", "starts with", and "ends with" from the filter options, and append a case insensitive regex search. We can rename the label to "Backup name / Shortname contains" and then the textbox.

We can even go as far to say, "if backadel exists, then print out 'Backup name /'", if we wanted to get more granular.

We can discuss it here.

**Comment by rrusso** [comment]
Kill the other options.

Remember, the granularity of contains is no smaller than username as it searches for _username. or _username_ in the filename of the backup.

**Comment by philcali** [comment]
Agreed. How do you feel @adamzap?

**Comment by adamzap** [comment]
I feel great.

Also, I think it's fine to remove that feature.

**Comment by rrusso** [comment]
@adamzap I was waiting for that.

Has Siri taken over your mind yet?

**Comment by philcali** [comment]
> I feel great.

:thumbsup:

**Comment by adamzap** [comment]
@rrusso I have only had incidental interaction with Siri but her charm and wit have already won me over.

:sparkles: Maybe I'll get to know her better one day :sparkles:

**Comment by philcali** [comment]
Discussion is moved to issue #13
