### ISSUE TITLE
Restore not working

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-block_simple_restore#14]
When using SR to restore, the system simply spins its wheels forever.

**Comment by philcali** [comment]
So this works for me, I guess I'll come check it out later.

**Comment by philcali** [comment]
Making some notes:
- In testing, the problem appears to be one related to permissions
- In testing, Robert found backadel backed up quizzes cause failure, and possibly anything backed up with user data

**Comment by rrusso** [comment]
No student data present in the archive.

**Comment by philcali** [comment]
Both problems may actually be a part of the same root problem. I'm about to make a pull request.

**Comment by rrusso** [comment]
Thanks!

**Comment by philcali** [comment]
Continued discussion on issue #15.
