### ISSUE TITLE
Overwrite Course Configuration

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-block_simple_restore#17]
When restoring via the restore process, the restorer has an option to overwrite course configuration.

This option should be set administratively in simple restore and the default should be yes.

This allows for topic courses to restore as topic courses and weekly courses to restore as weekly courses.

**Comment by philcali** [comment]
I'm on it :thumbsup:

**Comment by rrusso** [comment]
No rush.

**Comment by philcali** [comment]
Moving discussion to issue #18
