### ISSUE TITLE
unknown type

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-block_simple_restore#20]
Regular restore does not give this error.

error/restore_unknown_restore_type

When restoring as admin or instructor you get this error in SR.

You do not get this error via regular restore of the same exact course as instructor or admin.

**Comment by rrusso** [comment]
Assigning to adamzap due to phil not being in tomorrow.

**Comment by philcali** [comment]
I'd like to add: this behavior is currently only reproducible on 1.9 backups. In testing this is fine.

**Comment by rrusso** [comment]
Actually it does.

If you download a mbz and rename it to show in semester backups te same thing happens.
