### ISSUE TITLE
Overwrite current course does not work

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-block_simple_restore#24]
It imports.

**Comment by philcali** [comment]
I think what you may have been seeing was the fact that CPS interjection was overwriting the `sectioncache` with the previous course, so it the section contents themselves were not being removed / replaced. Anyway, this has been address with the latest CPS commit: https://github.com/lsuits/cps/commit/c6ca2ad3fd35e51d5da7aeb8143095c735179da7
