### ISSUE TITLE
Simple Restore needs access to secondary backup location

### ISSUE THREAD

**Issue by rrusso** [lsuits/lsu-block_simple_restore#3]
Please see https://github.com/lsuits/backadel/issues/2 for more details.
## Simple Restore immediate future needs
- Simple Restore needs to grab files from a pre-determined location using filename parsing.
  1. We have to be able to restore from our 1.9 backadel backups
  2. Current backups are stored on slow storage via a separate SAN mount.
  3. We have a need to be able to move from one Moodle instance to another without leaving the old one online forever.

**Comment by philcali** [comment]
This discussion will be continued in issue #6. Closing.
