### ISSUE TITLE
Simple Restore Decoupling CPS

### ISSUE THREAD

**Issue by philcali** [lsuits/lsu-block_simple_restore#7]
Currently, the enrollment is overridden when a restore of any kind is made. While this is correct Moodle behavior, it's not correct LSU behavior.

Correct decoupling can be handled through events. Enrollments can be recreated when the CPS block handles a simple restore event; the problem will still remain when an admin runs a regular restore. That's something I'm OK with living with.

**Comment by rrusso** [comment]
Agreed 100%

**Comment by rrusso** [comment]
Has this been addressed yet, @philcali?

**Comment by philcali** [comment]
No, but open sourcing the block is not dependent on this feature, so
I'm OK with rolling out final 1.0 until I have some time for CPS
integration.

On Mon, Oct 24, 2011 at 3:49 PM, Robert Russo
reply@reply.github.com
wrote:

> Has this been addressed yet, @philcali?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lsuits/simple_restore/issues/7#issuecomment-2509226

## 

Philip Cali

**Comment by rrusso** [comment]
Giddyup.

Just wanted to know if I needed to test for it yet.

**Comment by philcali** [comment]
This is no longer necessary: look at issue #18
